/**
 * Factory functions for creating transit config helpers
 *
 * Eliminates duplicate getLineCodes(), getLineConfig(), and calculateVehiclesPerDirection()
 * implementations across Metro, Tram, and FGC config files.
 */

import type { LineConfig } from '../types/transit';

/**
 * Helper functions generated by the factory
 */
export interface TransitConfigHelpers<T extends LineConfig> {
  /** Get all configured line codes */
  getLineCodes: () => string[];
  /** Get configuration for a specific line */
  getLineConfig: (lineCode: string) => T | undefined;
  /** Calculate vehicles per direction based on line length and headway */
  calculateVehiclesPerDirection: (lineLengthMeters: number, lineCode: string) => number;
}

/**
 * Creates helper functions for a transit line configuration
 *
 * @param config - Record of line code to line configuration
 * @returns Object with getLineCodes, getLineConfig, and calculateVehiclesPerDirection functions
 *
 * @example
 * ```typescript
 * const helpers = createConfigHelpers(METRO_LINE_CONFIG);
 * const codes = helpers.getLineCodes(); // ['L1', 'L2', ...]
 * const l1Config = helpers.getLineConfig('L1');
 * const trains = helpers.calculateVehiclesPerDirection(10000, 'L1');
 * ```
 */
export function createConfigHelpers<T extends LineConfig>(
  config: Record<string, T>
): TransitConfigHelpers<T> {
  return {
    getLineCodes: () => Object.keys(config),

    getLineConfig: (lineCode: string) => config[lineCode],

    calculateVehiclesPerDirection: (lineLengthMeters: number, lineCode: string) => {
      const lineConfig = config[lineCode];
      if (!lineConfig) return 0;

      // Convert speed to m/s
      const avgSpeedMs = (lineConfig.avgSpeedKmh * 1000) / 3600;

      // Time to traverse full line
      const tripTimeSeconds = lineLengthMeters / avgSpeedMs;

      // Number of vehicles needed to maintain headway
      const vehicles = Math.ceil(tripTimeSeconds / lineConfig.headwaySeconds);

      // Minimum 1 vehicle per direction
      return Math.max(1, vehicles);
    },
  };
}
